### ISSUE TITLE
document pls

### ISSUE THREAD

**Issue by trong291990** [phalcon-ext/widget-pagination#1]
How to use it pls

**Comment by KorsaR-ZN** [comment]
## Installing

Install composer in a common location or in your project:

```
curl -s http://getcomposer.org/installer | php
```

Create the composer.json file as follows:

```
{
    "require": {
        "phalcon-ext/widget-pagination": "dev-master"
    }
}
```

Run the composer installer:

``` bash
php composer.phar install
```

Add in your the code

```
require_once('vendor/autoload.php');
```

Add to the root folder of your views 
**./widgets/**[pagination.phtml](https://gist.github.com/KorsaR-ZN/7559e4e7be252d19e606)

## Using

_In controller_

``` php
$data = Products::find(['order' => 'name ASC']);
$paginator = new \Phalcon\Paginator\Adapter\Model([
      'data' => $data, 
      'limit' => 100, 
      'page' => (int)$_GET['page']
]);

$paginatorWidget = new PaginationWidget();
$paginatorWidget->setParams([
      'paginate' => $paginator //  Phalcon\Paginator\AdapterInterface
]);
$paginatorWidget->init();

$this->view->setVar('paginatorWidget', $paginatorWidget);
```

_In view_

``` php
<div> <?= $paginatorWidget->render() ?> </div>
```

**Comment by trong291990** [comment]
Thanks, :+1:

**Comment by trong291990** [comment]
Sorry it not work for me. I changed 
- undefined setParams method ->  edited to setOptions 
- undefined init method -> edited to onConstruct
- PaginationWidget line 150 : $_uri = parse_url($url ?: $_SERVER['HTTP_URI']);
  I changed to $_uri = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

And it works, Great widget. Thanks

**Comment by KorsaR-ZN** [comment]
@trong291990  I am sorry for the incorrect information.

You must use the so without manual call `onConstruct()` and `setOptions()`:

``` php
$paginatorWidget = new PaginationWidget([
      'paginate' => $paginator //  Phalcon\Paginator\AdapterInterface
]);
```
